// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcigC3SLksHAG2Bvqf7pvKGBKoR9CYItg',
    appId: '1:443332649473:web:3e71d1270d4a7d2eed5600',
    messagingSenderId: '443332649473',
    projectId: 'my-crypto-app-3778f',
    authDomain: 'my-crypto-app-3778f.firebaseapp.com',
    storageBucket: 'my-crypto-app-3778f.appspot.com',
    measurementId: 'G-BG140J12DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2nIZ3tVivfO97UFvh3z611Xk3uO4wGfI',
    appId: '1:443332649473:android:f912f4a722456c12ed5600',
    messagingSenderId: '443332649473',
    projectId: 'my-crypto-app-3778f',
    storageBucket: 'my-crypto-app-3778f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqFFZ3kKZqdmk7OBYsVPMG_9kvcT0GRuE',
    appId: '1:443332649473:ios:139ab3a18b78a0d2ed5600',
    messagingSenderId: '443332649473',
    projectId: 'my-crypto-app-3778f',
    storageBucket: 'my-crypto-app-3778f.appspot.com',
    iosClientId: '443332649473-injhq0qd03fc0tmh1pjn5vd2dqh0chr0.apps.googleusercontent.com',
    iosBundleId: 'br.com.rochajohnathan.crypoApp',
  );
}
